config/routes.rb
  get '/auth/:system_name/bounce' => 'provider/sessions#bounce', constraints: ProviderDomainConstraint, as: :authorization_provider_bounce

  namespace :provider, :path => 'p', constraints: MasterOrProviderDomainConstraint do
    get 'activate/:activation_code' => 'activations#create', :as => :activate

    resource :password, :only => %i(new show update destroy)
    resource :domains, :only => [:show] do
      collection do
        post :recover
      end
    end


    resource :signup, :only => [:show, :create] do
      match '', action: :cors, via: 'OPTIONS'
      match '*path', action: :cors, via: 'OPTIONS'

      collection do
        get :success
        get :test, as: :iframe
      end
    end

    # BEWARE: those 2 routes have to be below /p/signup/success or
    # they would override it.
    resource :invitee_signup, path: "signup/:invitation_token", only: [:show, :create]

    resource :sessions, :only => [:new, :create, :destroy, :show]
    get 'sso' => 'sessions#create'
    get 'login'  => 'sessions#new',     :as => :login
    get 'logout' => 'sessions#destroy', :as => :logout

    get 'admin', to: 'admin#show'

    namespace :admin do
      resource :sudo, only: [:new, :show, :create]

      resources :accounts, :only => [:new, :create]
      resources :authentication_providers do
        member do
          patch :publish_or_hide
        end
      end
      resource :dashboard, :only => [:show]

      namespace :dashboard do
        resource :new_accounts, only: [:show]
        resource :potential_upgrades, only: [:show]

        namespace :service, path: 'service/:service_id', as: :service do
          resource :hits, only: [:show]
          resource :integration_errors, only: [:show]
          resource :top_traffic, only: [:show], controller: :top_traffic
        end
      end

      resource :go_live_state, only: [:show, :update]
      resource :account, :only => [:show, :edit, :update]
      resource :api_docs, :only => [:show]
      resource :liquid_docs, :only => [:show]
      resource :webhooks, :only => [ :new, :edit, :create, :update, :show ]

      namespace :registry do
        constraints(id: /((?!\.json\Z)[^\/])+/) do
          resources :policies, except: %i[show delete]
        end
      end

      resources :destroys, :only => [:index]

      namespace :onboarding do
        namespace :wizard do
          root to: 'info#index'

          get 'intro' => 'info#intro'
          get 'explain' => 'info#explain'
          resource :api, only: [:new, :edit, :update], controller: :api
          resource :request, only: [:new, :edit, :update, :show], controller: :request
          get 'outro' => 'info#outro'
        end
      end

      namespace :messages do
        root to: 'inbox#index'
        resources :inbox, only: [:show, :destroy] do
          member do
            post :reply
          end
        end
        resources :outbox, except: [:edit, :update]
        resources :trash, only: [:index, :show, :destroy] do
          collection do
            delete :empty # delete all
          end
        end

        namespace :bulk do
          resource :trash, only: [:new, :create]
        end
      end

      namespace :api_docs do
        resource :account_data, :only => [:show]
        resources :specs, only: :show
      end

      scope 'applications/:application_id', :as => :application do
        resources :keys, :only => [ :new, :create, :edit, :update, :destroy ] do
          member do
            put :regenerate
          end
        end
        resources :referrer_filters, :only => [:create, :destroy]
      end

      namespace :cms do
        root to: 'templates#index'
        resources :templates, only: [:index] do
          collection do
            get :sidebar
          end

          resources :versions, only: [:index, :show, :destroy] do

            member do
              post :revert
            end
          end
        end

        resources :builtin_sections, controller: 'sections', except: [ :show, :destroy ]

        resources :sections, :except => [:show] do
          resources :changes
        end

        resources :builtin_static_pages, :builtin_pages, :builtin_partials, only: [:edit, :update] do
          member do
            put :publish
          end
        end

        resources :pages, :layouts, :partials, except: [:show, :index] do
          member do
            put :publish
          end
        end

        resources :email_templates, :except => [:show]
        resources :builtin_legal_terms, :except => [ :show, :index ]

        resources :portlets, :except => [:show] do
          collection do
            get :pick
          end
          member do
            put :publish
          end

        end

        resources :switches, :only => [ :index, :update, :destroy ]
        resources :files, :except => [:show]
        resources :redirects, :except => [:show]
        resources :sections, :except => [:show]
        resources :groups, :except => [:show]
        resources :changes do
          collection do
            put :publish_all
          end
          member do
            put :publish
            put :revert
          end

        end
      end

      namespace :user do
        resource :notification_preferences, only: [:show, :update]
        resource :personal_details, only: [:edit, :update]
        resources :access_tokens, only: [:index, :new, :create, :edit, :update, :destroy]
      end

      namespace :account do
        resources :authentication_providers do
          resource :publishing, :controller => 'authentication_provider_publishing', :only => [:create, :destroy]
          get :auth_show, controller: :authentication_provider_flow_testing, on: :member, as: :flow_testing_show
        end
        get '/callback/:system_name', action: :callback, controller: :authentication_provider_flow_testing, as: :flow_testing_callback

        resource :enforce_sso, :controller => 'enforce_sso', :only => [:create, :destroy]
        resources :notifications, :only => [:index, :update]
        resources :users, :only => [:index, :edit, :update, :destroy] do
          resources :access_tokens, only: [:index, :new, :create, :edit, :update, :destroy]
        end

        resource :braintree_blue, only: [:show, :edit, :update, :destroy], module: 'payment_gateways' do
          match 'hosted_success', via: [:get, :post], on: :member
        end
        resource :data_exports, :only => [:new, :create]
        resource :logo, only: %i[edit update destroy]

        resources :invitations, :only => [:index, :new, :create, :destroy] do
          member do
            put :resend
          end
        end

        resource :personal_details, only: [] do
          match '/', via: :any, to: redirect { Rails.application.routes.url_helpers.edit_provider_admin_user_personal_details_path }
          get 'edit', action: 'edit', on: :member, to: redirect { Rails.application.routes.url_helpers.edit_provider_admin_user_personal_details_path }
        end

        resource :change_plan, :only => [:show, :update] do
          member do
            get :widget
          end
        end

        resources :invoices, :only => [:show, :index]
      end

      namespace :service_discovery do
        resources :namespaces, only: [], controller: 'cluster_namespaces' do
          resources :services, only: [:index, :show], controller: 'cluster_services'
        end
        resources :projects, only: [:index], controller: 'cluster_projects'
        resources :services, only: [:create, :update]
      end
    end
  end

  namespace :api_docs do
    get 'track.:format' => 'tracking#update', :as => :check
  end

  # only for the admin/buyers stuff that dont have admin in route name
  namespace :buyers, :as => 'admin', :path => 'admin/buyers' do
    resources :account_plans, :only => [:new, :create, :edit, :update, :destroy] do
      collection do
        post :masterize
      end
      member do
        post :copy
      end
    end
  end

  # These are API routes, beware
  namespace :stats do
    namespace :data, :path => '' do
      # horrible hacks with path to get parameter to be named :service_id
      resources :services, :path => 'services/:service_id' do  #, :applications do
        collection do
          get 'usage'
          get 'usage_response_code'
          get 'top_applications'
          get 'summary'
        end
      end
      resources :applications, :path => 'applications/:application_id' do
        collection do
          get 'usage'
          get 'usage_response_code'
          get 'summary'
        end
      end
    end
  end

  get '/check.txt' => 'checks#check'
  get '/check/error' => 'checks#error'
  get '/search/forum' => 'search#forum'

  namespace :admin do # this is different from the scope that follows as the controllers are in the admin module

    namespace :account do
      resource :payment_gateway, :only => [:update]
    end

    namespace :api_docs do
      resources :services, controller: 'account_api_docs' do
        member do
          get :preview
          put :toggle_visible
        end
      end
    end

    resources :web_hooks, :only => [:index, :create, :update] do
      member do
        post :ping
      end
    end
    resource :user_confirmation, :only => :create
    resources :fields_definitions do
      collection do
        post :sort
      end
    end

    resources :upgrade_notices, :only => [:show]

    # api routes, be careful
    namespace :api, :defaults => { :format => 'xml' } do

      # called from heroku deploy hook after heroku proxy deploy script
      post 'heroku-proxy/deployed', to: 'heroku_proxy#deployed', as: :heroku_proxy_deployed

      namespace :personal, defaults: { format: :json } do
        resources :access_tokens, except: %i[new edit]
      end

      # /admin/api/provider
      resource :provider, only: [:show, :update]

      resources :authentication_providers, except: %i[new edit destroy]

app/controllers/provider/admin/keys_controller.rb
class Provider::Admin::KeysController < Provider::Admin::BaseController

  before_action :find_cinstance
  before_action :authorize_partners
  around_action :with_password_confirmation!

  def new
  end

  def edit
  end

  # user key
  def update
    @cinstance.user_key = params[:cinstance][:user_key]
    unless @cinstance.save
      flash.now[:error] = "Invalid key. Please review and try submitting again."
    end
    respond_to(:js)
  end

  def create
    @key = @cinstance.application_keys.add(params[:key])

    if @key.persisted?
      @keys = @cinstance.application_keys.pluck_values
    else
      flash.now[:error] = "Invalid key. Please review and try submitting again."
    end

    respond_to(:js)
  end

  def destroy
    @key = params[:id]
    @remove = @cinstance.application_keys.remove(@key)

    unless @remove
      flash.now[:error] = 'One application key minimum is required.'
    end

    respond_to(:js)
  end

  def regenerate
    @key = params[:id]

    @new_key = @cinstance.application_keys.regenerate(@key).value

    respond_to(:js)
  end

  private

  def authorize_partners
    authorize! :manage, :partners
  end

  def find_cinstance
    @cinstance = current_account.provided_cinstances.find(params[:application_id])
  end
end

app/views/provider/admin/keys/_key.html.erb
<%= content_tag(:tr, :id => "application_key_#{key.to_param}",
                :class => 'key', 'data-key' => key.to_param) do %>
  <td>Application key</td>
  <td class="key" <% if cinstance.backend_version.oauth? %>id="oauth_secret"<% end %>><%= key %>
    <%= content_tag(:span, :class => 'delete_key operations', :style => ("display:none;" unless cinstance.can_delete_key?)) do %>
      <% if cinstance.backend_version.oauth? %>
        <%= fancy_link_to("Regenerate", regenerate_provider_admin_application_key_path(:application_id => cinstance.id, :id => cinstance.keys.first),
                          :method => :put, :class => 'delete', :remote => true, id: 'regenerate-oauth-key')%>
      <% else %>
        <%= delete_link_for provider_admin_application_key_path(cinstance, key), :remote => true %>
      <% end %>
    <% end %>
  </td>
<% end %>

app/views/provider/admin/keys/_widget.html.erb
  <table id="keys" class="list">
    <%= render :partial => 'buyers/applications/api_credentials',
               :locals => {:cinstance => cinstance, :regenerate => true } %>
  </table>

  <% if cinstance.backend_version.v2? && cinstance.backend_version.app_keys_allowed? %>
    <table class="list">
      <tr>
        <td colspan="2" id="app-keys-operations" <%= "style=display:none;" unless cinstance.application_keys.can_add? %>>
          <% if cinstance.custom_keys_enabled? %>
            <%= link_to 'Add Custom key', new_provider_admin_application_key_path(cinstance),
                        :class => 'fancybox action add', 'data-autodimensions' => 'true' %>
          <% end -%>
          <%= link_to 'Add Random key', provider_admin_application_keys_path(cinstance),
                              :method  => :post,
                              :remote  => true,
                              :class   => 'create_key add action' %>
        </td>

        <% if cinstance.backend_version.v2? %>
          <td colspan="2" id="app-keys-limit-warning" <%= "style=display:none;" if cinstance.application_keys.can_add? %>;'>
            Keys limit reached.
          </td>
        <% end %>
      </tr>
    </table>
  <% end %>    

app/views/provider/admin/keys/create.js.erb
(function($) {
  var container = $("#application_keys");

  <% if @key.persisted? -%>
    $.colorbox.close();
    var keys = container.find("table#keys tbody");
    var key = <%= render_to_js_string('key', :cinstance => @cinstance, :key => @key) %>;
    $(key).hide().appendTo(keys.<%= @cinstance.backend_version.oauth? ? 'empty' : 'slice' %>()).fadeIn();

  <% else -%>
    $("#invalid-key-warning").text('<%= flash[:error] %>');
    $("#invalid-key-warning").show();
    $.colorbox.resize();
  <% end -%>

  <% unless @cinstance.application_keys.can_add? %>
    $('#app-keys-limit-warning').show(); // provider side
    $('#app-keys-operations').hide();
  <% end -%>

  container.find('.delete_key').<%= @cinstance.can_delete_key? ? 'fadeIn' : 'fadeOut' %>();
})(jQuery);

app/views/provider/admin/keys/destroy.js.erb
(function($) {
  var container = $("#application_keys");

  <%- if  @remove -%>
    container.find("#application_key_<%= escape_javascript(@key) %>").fadeOut(function() {
      $(this).remove();
    });
  <%- else -%>
    //alert('Mandatory at least one application key.')
    $.flash.error('<%= escape_javascript(flash.now[:error]) %>');
  <%- end -%>

  <%- if @cinstance.application_keys.can_add? -%>
    $('#app-keys-limit-warning').hide();     // provider side
    $('#app-keys-operations').show();

    container.find('.operations').enableSwitch(); // buyer side

  <%- else -%> // hide operations and show warning
    $('#app-keys-limit-warning').show(); // provider side
    $('#app-keys-operations').hide();

    container.find('.operations').disableSwitch(); // buyer side
  <%- end -%>

  container.find('.delete_key').<%= @cinstance.can_delete_key? ? 'fadeIn' : 'fadeOut' %>();

})(jQuery);

app/views/provider/admin/keys/edit.html.erb
<h2>Set Custom User Key</h2>

<p id="invalid-key-warning" style="display:none;">&nbsp;</p>

<%= semantic_form_for @cinstance, :url => provider_admin_application_key_path(@cinstance, @cinstance.user_key), remote: true do |form| %>
  <%= form.inputs do %>
    <%= form.input :user_key, :label => 'Custom User Key', :input_html => {:size => 100, :value => ''} %>
  <% end %>

  <%= form.buttons do %>
    <%= link_to 'Cancel', "#", :class => 'fancybox-close less-important-button' %>
    <%= form.commit_button 'Set Custom Key' %>
  <% end %>
<% end %>

app/views/provider/admin/keys/new.html.erb
<h2>Add key</h2>

<p id="invalid-key-warning" style="display:none;">&nbsp;</p>

<%= form_tag provider_admin_application_keys_path(@cinstance), :class => 'remote' do |form| %>
  <table class='plan-edit-popup'>
    <tr>
      <td style="vertical-align: top">
        <%= label_tag :key, "Key" %>
      </td>
      <td>
	  <%= text_field_tag :key, "", :class => 'text', :size => "40" %>
	      <p class="inline-hints">
          Only alphanumeric characters [0-9, a-z, A-Z], hyphen-minus (-),<br/>
	    between 5 and 256 characters long. No spaces allowed.</p>
      </td>
    </tr>

    <tr>
      <td>
        <%= link_to 'Cancel', "#", :class => 'fancybox-close less-important-button' %>
      </td>
      <td style="text-align: right;">
        <%= submit_tag "Save", :class => 'important-button' %>
      </td>
    </tr>
  </table>
<% end %>

app/views/provider/admin/keys/regenerate.js.erb
$("#oauth_secret").html(<%= @new_key.to_json.html_safe %>);
<%# replace url of form, so second regenerate works %>
$('#regenerate-oauth-key').attr('href', <%=regenerate_provider_admin_application_key_path(@cinstance, @new_key).to_json.html_safe %>);

app/views/provider/admin/keys/update.js.erb
  <% if @cinstance.valid? -%>
    $.colorbox.close();
    $('#cinstance-user-key').html('<%= @cinstance.user_key %>');
  <% else -%>
    $("#invalid-key-warning").text('<%= flash[:error] %>');
    $("#invalid-key-warning").show();
    $.colorbox.resize();
  <% end -%>